### ISSUE TITLE
S3 access changed for 0.3 version?

### ISSUE THREAD

**Issue by NiallWalshRAM** [alanhay/html-exporter#26]
Hi there, 

I'm currently using your library in a project I'm working on and since Friday, the github PR build is failing due to access issues with your s3 bucket.

`Failed to collect dependencies at uk:html-exporter:jar:0.3 -> com.osbcp:cssparser:jar:1.0: Failed to read artifact descriptor for com.osbcp:cssparser:jar:1.0: Could not transfer artifact com.osbcp:cssparser:pom:1.0 from/to maven-s3-release-repo (s3://alanhay-maven-repository/release): Cannot access s3://alanhay-maven-repository/release with type default using the available connector factories: BasicRepositoryConnectorFactory: Cannot access s3://alanhay-maven-repository/release using the registered transporter factories: HttpTransporterFactory, FileTransporterFactory, WagonTransporterFactory -> [Help 1]`

I can see the 0.3 version I'm using is still there - https://s3.console.aws.amazon.com/s3/buckets/alanhay-maven-repository?region=eu-west-1&prefix=release/uk/co/certait/html-exporter/0.3/&showversions=false 

Any help is greatly appreciated!

Niall

**Comment by alanhay** [comment]
Hi. I would suggest migrating to the latest version which has been changed to use an actively maintained CSS parser and which is published to Maven central thus removing the need for the S3 maven repo. This should be backwards compatible and fixes up a few other things.
