### ISSUE TITLE
Style is not working

### ISSUE THREAD

**Issue by SudhirSahoo** [alanhay/html-exporter#4]
I have below html string. I am expecting to see the text in excel to be underlined, but not working. tried adding style everywhere.

`String html = "<html><body style='text-decoration: underline;'><table style='text-decoration: underline;'><tr style='text-decoration: underline;'><td style='text-decoration: underline;'>Hello</td><td>Hello1</td></tr></body></html>";`

**Comment by alanhay** [comment]
You are missing a closing </table> tag. With that added it works fine for me with:

<td style='text-decoration: underline;'>Hello</td>

**Comment by alanhay** [comment]
Closing as not an issue.

**Comment by golimarrrr** [comment]
Is this color style format supported by html-exporter? The output cell is still black text on white background:
`<td id="f_1_7"  style="background-color: rgb(187, 255, 153);">CDANDE</td>`
