### ISSUE TITLE
Excel Export Error.

### ISSUE THREAD

**Issue by inetftp** [alanhay/html-exporter#6]
Is there any way to convert locally saved html file to Excel.
I tried to export excel but getting .css file error.
I don't want to genreateHtml method.
In this below method any way to  call a local html file that saved in directory.
new ExcelExporter().exportHtml();
Please suggest..

**Comment by inetftp** [comment]
I have used the below code 
    public static void main(String[] args) throws Exception {
        
        new ExcelExporter().exportHtml("D:\\INETPRJ\\REPORTS_DUMP\\itemPriceReport.html", new File("D:\\INETPRJ\\REPORTS_DUMP\\report.xlsx"));
System.exit(0);
        }

Below is the error code:-

Exception in thread "main" java.lang.NullPointerException
	at uk.co.certait.htmlexporter.writer.excel.ExcelExporter.exportHtml(ExcelExporter.java:57)
	at uk.co.certait.htmlexporter.writer.AbstractExporter.exportHtml(AbstractExporter.java:44)
	at ProgressIndicatorBean.view.HtmlExporter.<init>(HtmlExporter.java:10)
	at ProgressIndicatorBean.view.HtmlExporter.main(HtmlExporter.java:16)



Kindly Help....

**Comment by alanhay** [comment]
public void exportHtml(String html, OutputStream out) throws IOException 

The first argument is the String with the HTML. You are passing it a String with a file name. You need to read the contents of your file into a String and pass that. 

That is basic Java and I can't help you with that.

**Comment by tonyyl** [comment]
The ExcelExporter has some known defects about the html files' CSS terms,such as the color css attribute must be a hex number,"WHITE","RED" are not accepted,,which I encountered several times....

**Comment by tonyyl** [comment]
Continue with above,you have to manually fix the color words to hex numbers,or just remove them....
